TEAM_NAME = 'הפועל י-ם'
HOME_STADIUM = 'ירושלים איצטדיון טדי'

PLAYERS = {
    'אדבאיו אדליי': 'adeley_adebayo',
    'עומר אגבדיש': 'omer_agvadish',
    'תומר אלטמן': 'tomer_altman',
    'אווקה אשטה': 'awoke_eshetie',
    "אונדרז' באצ'ו": 'ondřej_bačo',
    'גיא בדש': 'guy_badash',
    'נואף בזיע': 'nwaf_baziaa',
    'גולן בני': 'golan_benny',
    'אופק ביטון': 'ofek_biton',
    "ג'ורדן בוטאקה": 'jordan_botaka',
    'עמית גלזר': 'amit_glazer',
    'נעם משה גרוס': 'noam_moshe_gross',
    'פלג חמני': 'peleg_hamani',
    "דור ג'אן": 'dor_jan',
    'גוני נאור': 'goni_naor',
    'עומר קבילו': 'omer_kabilo',
    'אלעד קפלן': 'elad_kaplan',
    'יוראי מליח': 'yorai_maliach',
    'נועם גיל מלמוד': 'noam_malamud',
    'נדב אביב נידם': 'nadav_niddam',
    'איינאו פרדה': 'aynao_preda',
    'רוי רביבו': 'roy_revivo',
    'יהונתן שאבי': 'yehonatan_shabi',
    'הראל שלום': 'harel_shalom',
    'ויליאם טוגי': 'william_togui',
    'יואב תומר': 'yoav_tomer',
    "אילוז' יאו": 'eloge_yao',
    'איתי זדה': 'itay_zada',
    'אחמד איברהים': 'achmed_salman',
    'דון סדריק': 'cedric_franck_don',
    'גיא חדידה': 'guy_hadida',
    "מאור ג'רסי": 'maor_gerassi',
    'קלטוס נומבייל': 'cletus_nombil',
    'וויליאם אגאדה': 'william_agada',
    'בן מיזן': 'ben_mizan',
    'לירן אלמליח': 'liran_elmaliah',
    'עידן שמש': 'idan_shemesh',
    'רוסלן ברסקי': 'roslan_barsky',
    'מידן יוסף כהן': 'meidan_cohen',
    'גל מאיו': 'gal_mayo',
    "חאמד שאולאג'ה": 'hamed_sholaja',
    'איהאב שאמי': 'eihab_shami',
    'סולומון דניאל': 'solomon_daniel',
    'אדוארדו גררו': 'eduardo_guerredo',
    'ברייט אנובקרה': 'bright_enobakhare',
    'אבירם זיאת': 'aviram_ziat',
    'כארם זועבי': 'karem_zoabi',
    'אלון אזוגי': 'alon_azugi',
    'בנימין טרידובסקי': 'beni_tridovski'

}

STADIUMS = {
    'ירושלים איצטדיון טדי': 'Teddy Stadium',
    'חיפה איצטדיון סמי עופר': 'Sammy Ofer Stadium',
    'בלומפילד': 'Bloomfield Stadium',
    'באר שבע איצטדיון טוטו ע"ש טרנר': 'Turner Stadium',
    'נתניה איצטדיון חדש': 'Netanya Stadium',
    'אצטדיון רמת גן': 'Ramat Gan Stadium',
    'אצטדיון המושבה': 'HaMoshava Stadium',
    'סכנין איצטדיון דוחא': 'Doha Stadium',
    'אצטדיון וינטר': 'Winter Stadium',
    'אשדוד': 'Yud-Alef Stadium',
    'אשדוד ': 'Yud-Alef Stadium',
    'אצטדיון השלום': 'HaShalom Stadium',
    'אצטדיון הברפלד': 'Haberfeld Stadium',
    'אצטדיון לויטה': 'Levita Stadium',
    'קרית שמונה': 'Kiryat Shmona Municipal Stadium',
    'אצטדיון סלה': 'Sala Stadium',
    'נוף הגליל איצטדיון גרין': 'Green Stadium',
    'אצטדיון טוטו עכו': 'Acre Municipal Stadium',
    'אצטדיון גרונדמן': 'Grundman Stadium',
    'אצטדיון שכונת התקווה': 'Hatikva Neighborhood Stadium',
    'האצטדיון העירוני נס ציונה': 'Ness Ziona Stadium',
    'האצטדיון העירוני חולון': 'Holon Municipal Stadium',
    'האצטדיון העירוני בת ים': 'Bat Yam Municipal Stadium',
    'האצטדיון העירוני לוד': 'Lod Municipal Stadium',
    'אצטדיון הלוחמים': 'HaLohamim Stadium',
    'האצטדיון העירוני עפולה': 'Afula Illit Stadium',
    'פתח תקוה איצטדיון שלמה ביטוח': 'HaMoshava Stadium'
}

TEAMS = {
    "הפ' נוף הגליל": "Hapoel Nof Hagalil",
    "הפועל י-ם": "Hapoel Jerusalem",
    "הפ' חדרה ש. שוורץ": "Hapoel Hadera Shulam Shwartz",
    'מכבי ת"א': "Maccabi Tel Aviv",
    'הפועל ב"ש': "Hapoel Beer Sheva",
    "מ.ס. אשדוד": "Football Club Ashdod",
    'הפועל ת"א': "Hapoel Tel Aviv",
    'בית"ר י-ם': "Beitar Jerusalem",
    "בני סכנין": "Bnei Sakhnin",
    'מכבי חיפה': "Maccabi Haifa",
    'מכבי ע. פ"ת': "Maccabi Ironi Petah Tikva",
    "מכבי נתניה": "Maccabi Netanya",
    'הפועל ק"ש': "Hapoel Kiryat Shmona",
    "הפועל חיפה": "Hapoel Haifa",
    "סקציה נס ציונה": "Sektzya Ness Ziona",
    "מכבי בני ריינה": "Maccabi Bnei Reine",
}

COACHES = {
    'ירון הוכנבוים': 'Yaron Hochenboim',
    'זיו אריה': 'Ziv Arieh',
    'קומאן ארווין': 'Arwoin Koman',
    'מנחם קורצקי': 'Menachem Koretsky',
    'שרון מימר': 'Sharon Mimer',
    'פטריק ון לוון': 'Patrick Van Leeuwen',
    'ברק בכר': 'Barak Bakhar',
    'רוני לוי': 'Roni Levy',
    'גיא לוזון': 'Guy Luzon',
    'בני לם': 'Beni Lam',
    'רן בן שמעון': 'Ran Ben Shimon',
    'סלובודן דראפיץ': 'Slavodan Drapez',
    'ניר קלינגר': 'Nir Klinger',
    'אלישע לוי': 'Elisha Levy',
    'יוסי מזרחי': 'Yossi Mizrahi',
    'מלאדן קרסטאיץ': 'Miladin Krestic',
    'קובי רפואה': 'Kobi Refua',
    'שי ברדה': 'Shay Barda',
    'יוסף אבוקסיס': 'Yosef Abukasis',
    'מורד מגמדוב': 'Morad Megamadov',
    'אסף נימני': 'Asaf Naimani',
    'חיים סילבס': 'Hayim Silvas',
    'אליניב ברדה': 'Eliniv Barda',
    'ניר ברקוביץ': 'Nir Berkovich',
    "ולדימיר איוויץ'": 'Vladimir Ivic',
    "רן קוז'וק": 'Ran Kozok',
    'ליאור זאדה': 'Lior Zada',
    'שלומי דורה': 'Shlomi Dora',
    'אייטור קראנקה': 'Aitor Karanka',
    '': ''
}
