TEAM_NAME = 'הפועל י-ם'
HOME_STADIUM = 'ירושלים איצטדיון טדי'

PLAYERS = {
    'אדבאיו אדליי': 'Adebayo ADELEYE',
    'עומר אגבדיש': 'Omer AGVADISH',
    'תומר אלטמן': 'Tomer ALTMAN',
    'אווקה אשטה': 'Awaka ASHTA',
    "אונדרז' באצ'ו": 'Ondrej BACO',
    'גיא בדש': 'Guy BADASH',
    'נואף בזיע': 'Nwaf BAZIAA',
    'גולן בני': 'Golan Beni',
    'אופק ביטון': 'Ofek BITON',
    "ג'ורדן בוטאקה": 'Jordan BOTAKA',
    'עמית גלזר': 'Amit GLAZER',
    'נעם משה גרוס': 'Noam Moshe GROSS',
    'פלג חמני': 'Peleg HAMANI',
    "דור ג'אן": 'Dor JAN',
    'גוני נאור': 'Goni NAOR',
    'עומר קבילו': 'Omer KABILO',
    'אלעד קפלן': 'Elad KAPLAN',
    'יוראי מליח': 'Yorai MALIAC',
    'נועם גיל מלמוד': 'Noam MELAMUD',
    'נדב אביב נידם': 'Nadav NIDAM',
    'איינאו פרדה': 'Aynao PRADA',
    'רוי רביבו': 'Roy REVIVO',
    'יהונתן שאבי': 'Yehonatan SHABI',
    'הראל שלום': 'Harel SHALOM',
    'ויליאם טוגי': 'William TOGUI',
    'יואב תומר': 'Yoav Tomer',
    "אילוז' יאו": 'Guy Eloge Koffi Yao',
    'איתי זדה': 'Itay ZADA',
    'אחמד איברהים': 'Ahmed Salman',
    'דון סדריק': 'Cedric Franck Don',
    'גיא חדידה': 'Guy Hadida',
    "מאור ג'רסי": 'Maor GEASSI',
    'קלטוס נומבייל': 'Cletus NOMBIL',
    'וויליאם אגאדה': 'William AGADA',
    'בן מיזן': 'Ben MIZAN',
    'לירן אלמליח': 'Liran ELMALIAH',
    'עידן שמש': 'Idan SHEMESH',
    'רוסלן ברסקי': 'Roslan BARSKI',
    'מידן יוסף כהן': 'Midan COHEN',
    'גל מאיו': 'Gal MAYO',
    "חאמד שאולאג'ה": 'Hamed SHOLAJA',
    'איהאב שאמי': 'Ehab SHAMI',
    'סולומון דניאל': 'Solomon DANIEL',
    'אדוארדו גררו': 'Eduardo GUERREDO',
    'ברייט אנובקרה': 'Bright ENOBAKHARE',
    'אבירם זיאת': 'Aviram ZIAT',
    'כארם זועבי': 'Karem ZOABI'
}

STADIUMS = {
    'ירושלים איצטדיון טדי': 'Teddy Stadium',
    'חיפה איצטדיון סמי עופר': 'Sammy Ofer Stadium',
    'בלומפילד': 'Bloomfield Stadium',
    'באר שבע איצטדיון טוטו ע"ש טרנר': 'Turner Stadium',
    'נתניה איצטדיון חדש': 'Netanya Stadium',
    'אצטדיון רמת גן': 'Ramat Gan Stadium',
    'אצטדיון המושבה': 'HaMoshava Stadium',
    'סכנין איצטדיון דוחא': 'Doha Stadium',
    'אצטדיון וינטר': 'Winter Stadium',
    'אשדוד': 'Yud-Alef Stadium',
    'אשדוד ': 'Yud-Alef Stadium',
    'אצטדיון השלום': 'HaShalom Stadium',
    'אצטדיון הברפלד': 'Haberfeld Stadium',
    'אצטדיון לויטה': 'Levita Stadium',
    'קרית שמונה': 'Kiryat Shmona Municipal Stadium',
    'אצטדיון סלה': 'Sala Stadium',
    'נוף הגליל איצטדיון גרין': 'Green Stadium',
    'אצטדיון טוטו עכו': 'Acre Municipal Stadium',
    'אצטדיון גרונדמן': 'Grundman Stadium',
    'אצטדיון שכונת התקווה': 'Hatikva Neighborhood Stadium',
    'האצטדיון העירוני נס ציונה': 'Ness Ziona Stadium',
    'האצטדיון העירוני חולון': 'Holon Municipal Stadium',
    'האצטדיון העירוני בת ים': 'Bat Yam Municipal Stadium',
    'האצטדיון העירוני לוד': 'Lod Municipal Stadium',
    'אצטדיון הלוחמים': 'HaLohamim Stadium',
    'האצטדיון העירוני עפולה': 'Afula Illit Stadium',
    'פתח תקוה איצטדיון שלמה ביטוח': 'HaMoshava Stadium'
}

TEAMS = {
    "הפ' נוף הגליל": "Hapoel Nof Hagalil",
    "הפועל י-ם": "Hapoel Jerusalem",
    "הפ' חדרה ש. שוורץ": "Hapoel Hadera Shulam Shwartz",
    'מכבי ת"א': "Maccabi Tel Aviv",
    'הפועל ב"ש': "Hapoel Beer Sheva",
    "מ.ס. אשדוד": "Football Club Ashdod",
    'הפועל ת"א': "Hapoel Tel Aviv",
    'בית"ר י-ם': "Beitar Jerusalem",
    "בני סכנין": "Bnei Sakhnin",
    'מכבי חיפה': "Maccabi Haifa",
    'מכבי ע. פ"ת': "Maccabi Ironi Petah Tikva",
    "מכבי נתניה": "Maccabi Netanya",
    'הפועל ק"ש': "Hapoel Kiryat Shmona",
    "הפועל חיפה": "Hapoel Haifa",
    "סקציה נס ציונה": "Sektzya Ness Ziona",
    "מכבי בני ריינה": "Maccabi Bnei Reine",
}

COACHES = {
    'ירון הוכנבוים': 'Yaron Hochenboim',
    'זיו אריה': 'Ziv Arieh',
    'קומאן ארווין': 'Arwoin Koman',
    'מנחם קורצקי': 'Menachem Koretsky',
    'שרון מימר': 'Sharon Mimer',
    'פטריק ון לוון': 'Patrick Van Leeuwen',
    'ברק בכר': 'Barak Bakhar',
    'רוני לוי': 'Roni Levy',
    'גיא לוזון': 'Guy Luzon',
    'בני לם': 'Beni Lam',
    'רן בן שמעון': 'Ran Ben Shimon',
    'סלובודן דראפיץ': 'Slavodan Drapez',
    'ניר קלינגר': 'Nir Klinger',
    'אלישע לוי': 'Elisha Levy',
    'יוסי מזרחי': 'Yossi Mizrahi',
    'מלאדן קרסטאיץ': 'Miladin Krestic',
    'קובי רפואה': 'Kobi Refua',
    'שי ברדה': 'Shay Barda',
    'יוסף אבוקסיס': 'Yosef Abukasis',
    'מורד מגמדוב': 'Morad Megamadov',
    'אסף נימני': 'Asaf Naimani',
    'חיים סילבס': 'Hayim Silvas',
    'אליניב ברדה': 'Eliniv Barda',
    'ניר ברקוביץ': 'Nir Berkovich',
    "ולדימיר איוויץ'": 'Vladimir Ivic',
    "רן קוז'וק": 'Ran Kozok',
    'ליאור זאדה': 'Lior Zada',
    'שלומי דורה': 'Shlomi Dora',
    'אייטור קראנקה': 'Aitor Karanka',
    '': ''
}
